### ISSUE TITLE
Run pre-merge tests

### ISSUE THREAD

**Issue by MarcSkovMadsen** [panel-extensions/copier-template-panel-extension#12]
When making a PR the tests don't seem to run:

![image](https://github.com/user-attachments/assets/8ff86229-81ff-441d-bff5-94cea38a5409)

https://github.com/awesome-panel/panel-copy-paste/pull/2

**Comment by hoxbro** [comment]
I'm pretty sure this is needed in the ci.yaml. 

``` yaml
  pull_request:
    branches:
      - "*"
```
